version: "3.7"

services:
    flask:
        container_name: flask-container
        build:
            context: ../
            dockerfile: deploy/service.Dockerfile
        ports:
            - 5000:5000
        depends_on:
            - db
        links:
            - db

    db:
        container_name: dgraph-container
        build:
            context: ../
            dockerfile: deploy/db.Dockerfile
        volumes:
            - /mnt/dgraph:/dgraph
        ports:
            - 8080:8080
            - 9080:9080
            - 8000:8000
        restart: on-failure